# Generated by Django 2.2.1 on 2019-05-29 02:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190527_0433'),
        ('restaurants', '0003_auto_20190528_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='customers',
            field=models.ManyToManyField(related_name='tables', to='users.Customer'),
        ),
        migrations.AddField(
            model_name='table',
            name='ordered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
