# Generated by Django 2.2.1 on 2019-06-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20190602_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabitem',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
