# Generated by Django 2.2.1 on 2019-06-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_tabitem_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabitem',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=6),
        ),
    ]
