# Generated by Django 2.2.1 on 2019-06-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_auto_20190606_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
