# Generated by Django 2.2.1 on 2019-11-18 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_tab_paid_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='restaurants.Restaurant'),
        ),
        migrations.AlterField(
            model_name='tabitem',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_items', to='restaurants.Tab'),
        ),
    ]
