# Generated by Django 2.2.1 on 2019-05-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='referral_code',
            field=models.CharField(default='40424D7', editable=False, max_length=7, unique=True),
        ),
    ]
