# Generated by Django 2.2.1 on 2019-05-27 04:33

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190527_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='referral_code',
            field=models.CharField(default=users.models.generate_referral_code, editable=False, max_length=7, unique=True),
        ),
    ]
