# Generated by Django 2.2.1 on 2019-06-02 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20190602_2045'),
        ('users', '0003_auto_20190527_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.Tab'),
        ),
    ]
