# Generated by Django 2.2.1 on 2019-11-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customer_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='stripe_access_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='stripe_user_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
