# Generated by Django 2.2.1 on 2019-12-29 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_auto_20191118_1820'),
        ('users', '0005_auto_20191118_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='restaurant',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant'),
            preserve_default=False,
        ),
    ]
